AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge RuleDetectEC2Creation
Resources:
  Rule0739bfa4:
    Type: AWS::Events::Rule
    Properties:
      Name: DetectEC2Creation
      EventPattern: >-
        {"source":["aws.ec2"],"detail-type":["AWS API Call via
        CloudTrail"],"detail":{"eventSource":["ec2.amazonaws.com"],"eventName":["RunInstances"],"userIdentity":{"sessionContext":{"sessionIssuer":{"userName":[{"anything-but":["aws-batch","AWSServiceRoleForBatch"]}]}}}}}
      State: ENABLED
      Description: >-
        Notificación automática que se activa cuando se detecta la creación de
        nuevas instancias en AWS. Esta alerta permite monitorear y auditar la
        infraestructura en tiempo real, asegurando control y seguridad en los
        despliegues.
      EventBusName: default
      Targets:
        - Id: Id47f7925b-e77c-4599-948f-cd4471e5c064
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:utp-dev-notification-instance-creation-topic
          InputTransformer:
            InputPathsMap:
              accountId: $.account
              arn: $.detail.userIdentity.arn
              availabilityZone: >-
                $.detail.responseElements.instancesSet.items[0].placement.availabilityZone
              eventTime: $.detail.eventTime
              imageId: $.detail.responseElements.instancesSet.items[0].imageId
              instanceId: $.detail.responseElements.instancesSet.items[0].instanceId
              instanceType: $.detail.responseElements.instancesSet.items[0].instanceType
              launchTime: $.detail.responseElements.instancesSet.items[0].launchTime
              principalId: $.detail.userIdentity.principalId
              privateIpAddress: $.detail.responseElements.instancesSet.items[0].privateIpAddress
              securityGroupId: >-
                $.detail.responseElements.instancesSet.items[0].groupSet.items[0].groupId
              securityGroupName: >-
                $.detail.responseElements.instancesSet.items[0].groupSet.items[0].groupName
              sourceIPAddress: $.detail.sourceIPAddress
              subnetId: $.detail.responseElements.instancesSet.items[0].subnetId
              userName: $.detail.userIdentity.sessionContext.sessionIssuer.userName
              vpcId: $.detail.responseElements.instancesSet.items[0].vpcId
            InputTemplate: |-
              {
                "🚨🚨 event": "Creación de Instancia DEV - EC2 🚨🚨",
                "⚙️ accountId": "<accountId>",
                "instanceDetails": {
                  "🆔 instanceId": "<instanceId>",
                  "📷 amiId": "<imageId>",
                  "⚙️ instanceType": "<instanceType>",
                  "⏳ launchTime": "<launchTime>",
                  "🚀 subnetId": "<subnetId>",
                  "🏢 vpcId": "<vpcId>"
                },
                "user": {
                  "📌 userName": "<userName>",
                  "👨‍💻 principalId": "<principalId>",
                  "⚡ arn": "<arn>",
                  "🌍 sourceIPAddress": "<sourceIPAddress>"
                },
                "📆 eventTime": "<eventTime>"
              }
Parameters: {}
